/*
 * Automatically generated by docopt_c.py (JCF's version)
 */

#ifndef __DOCOPTOUT_H
#define __DOCOPTOUT_H

typedef struct {$commands$arguments$flags$options
    /* special */
    const char *usage_pattern;
    const char *help_message;
} DocoptArgs;

DocoptArgs docopt(int argc, char *argv[], bool help, const char *version);


#endif /* __DOCOPTOUT_H */
